server:
  port: 5555

spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:                         #Необходимо внести соотв. изменения, по мере найстройки других сервисов
        - id: auth-service              #Порт соединения. Context path
          uri: http://localhost:8191
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
            - PrefixPath=/ff-auth
            - JwtAuthFilter
#            - - RoleAuth=ADMIN
        - id: PersonalArea
          uri: http://localhost:8192
          predicates:
            - Path=/personalarea/**
          filters:
            - StripPrefix=1
            - PrefixPath=/ff-personalarea
            - JwtAuthFilter
        - id: rest
          uri: http://localhost:8189
          predicates:
            - Path=/rest/**
          filters:
            - StripPrefix=1
            - PrefixPath=/ff-restaurants
            - JwtAuthFilter
        - id: menu
          uri: http://localhost:8194
          predicates:
            - Path=/menu/**
          filters:
            - StripPrefix=1
            - PrefixPath=/ff-menu
            - JwtAuthFilter


jwt:
  secret: h4f8093h4f983yhrt9834hr0934hf0hf493g493gf438rh438th34g34g