server:
  port: 5555

spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "*"
      routes:                         #Необходимо внести соотв. изменения, по мере найстройки других сервисов
        - id: auth              #Порт соединения. Context path
          uri: http://localhost:8100
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
            - PrefixPath=/ff-auth
            - JwtAuthFilter
        #            - - RoleAuth=ADMIN
        - id: PersonalArea
          uri: http://localhost:8188
          predicates:
            - Path=/personal/**
          filters:
            - StripPrefix=1
            - PrefixPath=/ff-personal
            - JwtAuthFilter
        - id: rest
          uri: http://localhost:8189
          predicates:
            - Path=/rest/**
          filters:
            - StripPrefix=1
            - PrefixPath=/ff-restaurants
            - JwtAuthFilter
        - id: menu
          uri: http://localhost:8187
          predicates:
            - Path=/menu/**
          filters:
            - StripPrefix=1
            - PrefixPath=/ff-menu
            - JwtAuthFilter


jwt:
  secret: 3979244226452948404D635166546A576E5A7234753778214125432A462D4A61